### ISSUE TITLE
Claim of 50% performance increase over Rust in Modular article

### ISSUE THREAD

**Issue by nbars** [MoSafi2/BlazeSeq#2]
Hey, I am wondering why the [article](https://www.modular.com/blog/outperforming-rust-benchmarks-with-mojo) on the Modular website states that this Mojo implementation is 50% faster than the Rust equivalent, even though this repository only claims to be on par with Rust ("and similair performance to rust's ultra-fast Needletail in FASTQ parsing"). Also, was this implementation tested for correctness and not developed with only speed in mind?

Best,
Nils

**Comment by MoSafi2** [comment]
@nbars I think currently the testing machine archeticture play a role. on older Intels or Mac (+ apple silicon) there is a consistent 25-50% increase in performance. on my machine (Intel i7-13700K + Samsung 980 NVME SSD) there is no major difference in worst case scenario which I included in the benchmarks (So you shouldn't get worse results). I don't really have maximum speed in mind (but it is a nice side effect to have) so my implementations are deliberately similair to Needletail for fast parsing and also using the same algorithm for quality trimming as Cutadapt and I didn't implement alternative algorthims to ensure correctness without the need for extensive validation experiments with real-world and synthetic data.
This is  more of less experimenting with Mojo itself and any performance gains is probably due to the Mojo compiler being based on newer technology as the MLIR infrasturcutre.  Hopefully if Mojo matures enough, this experimental project can one of the basic building blocks for  a BioMojo kind of eco-system.

**Comment by nbars** [comment]
Thanks for the clarification! You could go with differentially testing inputs with already established implementations. Overall, your article on Modular gives a wrong impression of what Mojo is actually capable of and gives it credit for an improvement that is very likely due to the platform it is running on. Still, it is impressive if it is on par, but the current statements are just misleading, and as you also removed those from the repository's readme, you may agree.

**Comment by wiseaidev** [comment]
> even though this repository only claims to be on par with Rust

Indeed. Moreover, the observed variations in measurements seem to exhibit some degree of noise. Additionally, the code's author did not provide explicit details regarding their benchmarking methodology, leaving uncertainties about whether they used `cargo bench` or simply timed the execution using the `time` command. Given the lack of clarity in the benchmarking methodology, it would be unfair to pass judgment on Rust based on benchmarking practices that lack transparency.

Furthermore, the following refactored code reveals certain inefficiencies, such as unnecessary type casting, `as u64`, and the inclusion of a `n + 1` instruction within the main loop, along with a pointless `print` statement.

https://github.com/MoSafi2/MojoFastTrim/blob/709cf4d698465674d3829a073e91c945215bcd7b/benchmark/needletail_benchmark/src/main.rs#L10-L18

It is noteworthy that the use of a `while` loop is discouraged in performance-critical situations in any programming language, including Rust. These code improvements are aimed at enhancing both readability and performance.

```rust
use needletail::parse_fastx_file;
use std::env;

fn main() {
    if let Some(path) = env::args().nth(1) {
        let (mut _slen, mut _qlen) = (0usize, 0usize);
        if let Ok(mut reader) = parse_fastx_file(&path) {
            for _ in 0.. { // equivalent to loop {}
                match reader.next() {
                    Some(record) => {
                        let seqrec = record.expect("invalid record");
                        _slen += seqrec.seq().len();
                        _qlen += seqrec.qual().map_or(0, |qual| qual.len());
                    }
                    None => break,
                }
            }
        } else {
            eprintln!("Error: Unable to parse the provided file");
            std::process::exit(1);
        }
    } else {
        eprintln!("Usage: {} <in.fq>", file!());
        std::process::exit(1);
    }
}
```

The main loop now accumulates sequence and quality lengths without the need for unnecessary casting or incrementing `n + 1`. Moreover, if the intention is to conduct benchmarks, the usage of `print` statements raises questions. Furthermore, leveraging Rust's special function, `black_box`, can precisely time the computations within the main loop, mitigating potential noise and offering more accurate benchmark results.

```rust
use needletail::parse_fastx_file;
use needletail::FastxReader;
use std::hint::black_box;
use std::time::{Duration, Instant};

fn main() {
    if let Some(path) = std::env::args().nth(1) {
        const NUM_ITERATIONS: u32 = 1000;
        let mut total_duration = Duration::new(0, 0);

        for _ in 0..NUM_ITERATIONS {
            let reader = parse_fastx_file(&path).expect("valid path/file");
            let start_time = Instant::now();
            black_box(process_records(black_box(reader)));
            total_duration += start_time.elapsed();
        }
        let average_duration = total_duration / NUM_ITERATIONS;
        println!("Average time execution: {:?}", average_duration);
    } else {
        eprintln!("Usage: {} <in.fq>", file!());
        std::process::exit(1);
    }
}

fn process_records(mut reader: Box<dyn FastxReader>) -> (usize, usize) {
    let mut slen = 0usize;
    let mut qlen = 0usize;

    loop {
        // same as for _ in 0..
        match reader.next() {
            Some(record) => {
                let seqrec = record.expect("invalid record");
                slen += seqrec.seq().len();
                qlen += seqrec.qual().map_or(0, |qual| qual.len());
            }
            None => break,
        }
    }

    (slen, qlen)
}

// cargo run --release -- 9_Swamp_S2B_rbcLa_2019_minq7.fastq

// Average time execution: 8.484332 ms
```

When running this program with `40k` reads, the Rust version exhibits an approximate runtime of ~8.48 milliseconds on an old 4-core Intel machine. This suggests that the Rust implementation is more than twice as fast as its Mojo counterpart. It's crucial to recognize that directly comparing this performance with Mojo might appear unfair, as Mojo is CUDA/GPU-oriented, inherently optimized for a different kind of processing. Rust, on the other hand, operates as a purely CPU-oriented programming language, though it offers GPU support.

Furthermore, it's essential to note that comparing the performance of both Rust and Mojo libraries is inherently unfair, as they represent two completly different implementations. To ensure a meaningful comparison, it is imperative to first verify that both implementations share the same underlying structures and algorithm. Without such alignment in implementations, any performance analysis may yield inaccurate or misleading results.

Personally, I don't think I am going to use Mojo in the near future, primarily because it is proprietary software. Unless it undergoes a transition to an open-source model, it's unlikely to be part of my toolkit. The preference for open-source solutions aligns with my values and ensures a more transparent and community-driven approach to software development.

Best,
_Rust all the things_

**Comment by MoSafi2** [comment]
@nbars I am not sure that the article is misleading or the the performance gain can be attributed to just noise. 
While I am using the same parsing algorithm as `needletail`, the language-specific implementation and optimizations is NOT the same. for example Mojo support for `SIMD` is much better than Rust in my opinion. 
the `memchr` crate which provides the SIMD string search co-routines for example has 3 implementation for each function, one for each procesor architecture, it also uses a lot of magic number for search window width and when to use the iterative vs the vectorized version. maybe this can be useful, but it is highly complicated code which relies on processor intrinstics, unsafe rust, and compilation fallbacks.
For mojo, the implementation of SIMD memchr is quite simple. The SIMD register width is interrograted as a compile-time function which results in a architecture-indepedent code that does not need to be specialized or purpose built and it is suifficent for my purposes.
```python
#The same function which can be run on ARM, Intel, or Apple silicon arcs
@always_inline
fn find_chr_next_occurance_simd[T: DType](in_tensor: Tensor[T], chr: Int, start: Int = 0) -> Int:
    let len = in_tensor.num_elements() - start
    let aligned = start + math.align_down(len, simd_width)

    for s in range(start, aligned, simd_width):
        let v = in_tensor.simd_load[simd_width](s)
        let mask = v == chr
        if mask.reduce_or():
            return s + arg_true(mask)

    for i in range(aligned, in_tensor.num_elements()):
        if in_tensor[i] == chr:
            return i
    return -1
```
The result is quite consistent performance for `MojoFastTrim` which on Mac M2 or Intel-i7 13700-K (two processor with comparable single-core performance) have the same performance (220ms for 1.3G file, 5.5M reads) while on Rust's shows arbitary slow-downs where it is on Apple M2 were 50% slower than on 13th-gen Intel. The same with my older 8th-gen Intel. Also, even on my 13th-gen Intel test machine I have noticed some compilation happy paths for rust, with 1 of every 3 or 4 time I compile the rust snippet, it also shows around 30% decreased performance. If on 2/3 test machines there is a consistent performance gain, I think this points to compiler or language-specific optimization rather than performance noise. 

Finally, curshing benchmarks or optimizing for speed-ups is not really my goal really with this project, that's why I didn't cherry pick any benchmarks. I enjoy Mojo because of the ease of use, the promised scalibility. This is 1st low-level language that I can both write really nice performant code in but I still can prototype my function in Jupyter notebook and has a syntax which is accessible to the average python dev. Accessability and stack unificiation is I think the main goal of my work here. I hope for your understaning of that :)

**Comment by MoSafi2** [comment]
@wiseaidev I now added the code used for benchmarking in the `benchmark` folder. Please feel free to replicate the results and I would happily accept your benchmarks as well. 
For the rust implementation, the implmenation is per the [BioFast benchmark](https://github.com/lh3/biofast/) which specifies that each run should accumulate the number of reads, sequence and quality string lengths and print the results at the end. Which is the same approch that was also used for `MojoFastTrim`. If your code meets those conditions, please feel free to submit a PR. 
However, there can be no spefication for the length of the loop (the length of the Fastq file is unknow and can be just a continuous I/O stream) also the number of bases is unknown and can be in the billions which can cause an overflow in 32-bit accumulators.

**Comment by yuribudilov** [comment]
it seems to me that the title of the article on Modular site (Mojo 50% faster than Rust) is quite misleading.

**Comment by nyabinary** [comment]
> > even though this repository only claims to be on par with Rust
> 
> Indeed. Moreover, the observed variations in measurements seem to exhibit some degree of noise. Additionally, the code's author did not provide explicit details regarding their benchmarking methodology, leaving uncertainties about whether they used `cargo bench` or simply timed the execution using the `time` command. Given the lack of clarity in the benchmarking methodology, it would be unfair to pass judgment on Rust based on benchmarking practices that lack transparency.
> 
> Furthermore, the following refactored code reveals certain inefficiencies, such as unnecessary type casting, `as u64`, and the inclusion of a `n + 1` instruction within the main loop, along with a pointless `print` statement.
> 
> https://github.com/MoSafi2/MojoFastTrim/blob/709cf4d698465674d3829a073e91c945215bcd7b/benchmark/needletail_benchmark/src/main.rs#L10-L18
> 
> It is noteworthy that the use of a `while` loop is discouraged in performance-critical situations in any programming language, including Rust. These code improvements are aimed at enhancing both readability and performance.
> 
> ```rust
> use needletail::parse_fastx_file;
> use std::env;
> 
> fn main() {
>     if let Some(path) = env::args().nth(1) {
>         let (mut _slen, mut _qlen) = (0usize, 0usize);
>         if let Ok(mut reader) = parse_fastx_file(&path) {
>             for _ in 0.. { // equivalent to loop {}
>                 match reader.next() {
>                     Some(record) => {
>                         let seqrec = record.expect("invalid record");
>                         _slen += seqrec.seq().len();
>                         _qlen += seqrec.qual().map_or(0, |qual| qual.len());
>                     }
>                     None => break,
>                 }
>             }
>         } else {
>             eprintln!("Error: Unable to parse the provided file");
>             std::process::exit(1);
>         }
>     } else {
>         eprintln!("Usage: {} <in.fq>", file!());
>         std::process::exit(1);
>     }
> }
> ```
> 
> The main loop now accumulates sequence and quality lengths without the need for unnecessary casting or incrementing `n + 1`. Moreover, if the intention is to conduct benchmarks, the usage of `print` statements raises questions. Furthermore, leveraging Rust's special function, `black_box`, can precisely time the computations within the main loop, mitigating potential noise and offering more accurate benchmark results.
> 
> ```rust
> use needletail::parse_fastx_file;
> use needletail::FastxReader;
> use std::hint::black_box;
> use std::time::{Duration, Instant};
> 
> fn main() {
>     if let Some(path) = std::env::args().nth(1) {
>         const NUM_ITERATIONS: u32 = 1000;
>         let mut total_duration = Duration::new(0, 0);
> 
>         for _ in 0..NUM_ITERATIONS {
>             let reader = parse_fastx_file(&path).expect("valid path/file");
>             let start_time = Instant::now();
>             black_box(process_records(black_box(reader)));
>             total_duration += start_time.elapsed();
>         }
>         let average_duration = total_duration / NUM_ITERATIONS;
>         println!("Average time execution: {:?}", average_duration);
>     } else {
>         eprintln!("Usage: {} <in.fq>", file!());
>         std::process::exit(1);
>     }
> }
> 
> fn process_records(mut reader: Box<dyn FastxReader>) -> (usize, usize) {
>     let mut slen = 0usize;
>     let mut qlen = 0usize;
> 
>     loop {
>         // same as for _ in 0..
>         match reader.next() {
>             Some(record) => {
>                 let seqrec = record.expect("invalid record");
>                 slen += seqrec.seq().len();
>                 qlen += seqrec.qual().map_or(0, |qual| qual.len());
>             }
>             None => break,
>         }
>     }
> 
>     (slen, qlen)
> }
> 
> // cargo run --release -- 9_Swamp_S2B_rbcLa_2019_minq7.fastq
> 
> // Average time execution: 8.484332 ms
> ```
> 
> When running this program with `40k` reads, the Rust version exhibits an approximate runtime of ~8.48 milliseconds on an old 4-core Intel machine. This suggests that the Rust implementation is more than twice as fast as its Mojo counterpart. It's crucial to recognize that directly comparing this performance with Mojo might appear unfair, as Mojo is CUDA/GPU-oriented, inherently optimized for a different kind of processing. Rust, on the other hand, operates as a purely CPU-oriented programming language, though it offers GPU support.
> 
> Furthermore, it's essential to note that comparing the performance of both Rust and Mojo libraries is inherently unfair, as they represent two completly different implementations. To ensure a meaningful comparison, it is imperative to first verify that both implementations share the same underlying structures and algorithm. Without such alignment in implementations, any performance analysis may yield inaccurate or misleading results.
> 
> Personally, I don't think I am going to use Mojo in the near future, primarily because it is proprietary software. Unless it undergoes a transition to an open-source model, it's unlikely to be part of my toolkit. The preference for open-source solutions aligns with my values and ensures a more transparent and community-driven approach to software development.
> 
> Best, _Rust all the things_

Aren't you the person that did those LLM RFCs lol

**Comment by MoSafi2** [comment]
As the issue was answered and there is no repo-related discussion, I will close the issue

**Comment by wiseaidev** [comment]
> Aren't you the person that did those LLM RFCs lol

I typically don't engage with comments that seem to lack effort, like the one you provided. It's not because I'm unwilling, but rather due to time constraints from my multiple part-time jobs and intensive involvement in Open Source projects. While nobody explicitly asked for it, if I see an opportunity for improvement, I act on it driven by personal aspirations.

Regarding your comment, given its positive number of engagement, and going back to your remarks on the LLMazing/LLM RFCs joke, during that period, software engineering seemed dead to me, both internally and externally, with AI playing a significant role. Consequently, I chose to create a meme as a way to express my feelings. Though this decision led to the loss of some friendships, it was a deliberate choice fueled by my desire for change. Now, addressing both the repository and your comment, I won't spend too much time criticizing the subpar quality of both, falling below the capabilities of gpt-3. Instead, I recommend objectively comparing both languages before jumping to conclusions. Next time, invest time and effort into comprehensive research on such topics.

Back to Mojo, it's crucial to note that Modular failed to fulfill its promises about open-sourcing their code, providing nonsensical excuses like [it's a big project](https://docs.modular.com/mojo/faq.html#why-not-develop-mojo-in-the-open-from-the-beginning) (it has been a year so far, btw!). Consequently, I won't use it due to its closed-source nature, especially with viable open-source alternatives available, with Rust being a notable example. Modular's lack of commitment to open-source their programming language makes it clear that Mojo won't find a place in my toolkit anytime soon, as mentioned in a previous comment.

I encourage you to reconsider and approach discussions with a more thorough and informed perspective, taking the time to research and analyze topics comprehensively.

Try Again,
_Rust all the things_
